### ISSUE TITLE
Album Art

### ISSUE THREAD

**Issue by sheik124** [th3-z/fb2k-mini-player#2]
Thank you for making this, it's flippin' awesome while gaming.

Is the album art behavior hard-coded? I have foobar's Album Art setting to "Prefer Embedded" and the mini-player seems to only stick to "Prefer External" - album folders without images in them just show the neon green foobar logo in the miniplayer UI.

**Comment by sheik124** [comment]
Just looked at the only other issue from a year ago and saw that album art was discussed. Maybe it's an issue with how the COM Automation plugin prioritizes Album Art.

I did find a temporary bodge of a workaround for one of the issues where it would pull whatever image Windows decided should be "Folder.jpg" for a folder filled with music that all has different album art...delete folder.jpg and stop Windows from re-creating it by changing the view settings for said folder.

**Comment by z3ath** [comment]
Hi,

It's not the COM automation plug-in, the album art is picked up by this software. It looks for common album art names like `front.png` first, if it fails to find anything it _should_ check the file tags for album artwork, if this fails to find anything it'll show that foobar logo instead. 

It sounds like in your case it's failing to find the embedded artwork at all?

I don't think there's an easy way for me to grab the preference from foobar but I could probably add a config option to prefer the embedded artwork.

**Comment by sheik124** [comment]
Wasn't expecting a response!

Yeah, in foobar's Advanced menu, under Display -> Album Art, I believe it defaults to "Prefer larger" but there are also options for "Prefer embedded" and "Prefer external."

Now that I know it's pulling album art on its own, that explains it. I don't expect it to grab foobar's preference if that's too difficult, but having it prioritize embedded album art would eliminate all of the problems where Windows has decided it ought to generate a "Folder.jpg" that's the wrong image (unavoidable with "Music" folders that have a mix of files in there).

I double checked the files where I saw the foobar logo, and the tags were messed up. Re-attaching the album art to those songs fixed it.

Only issue now is those mixed folders like I mentioned, a config option would be great. I tried to poke around in all of the files to see if it was something I could figure out and gave up.

**Comment by sheik124** [comment]
On a somewhat related note, the only files with embedded artwork that still don't display album art (wasn't all of them, kept clicking through my playlist) are FLAC or M4A files, either AAC or Apple Lossless. It can't see the same image that foobar shows present in the tags as "Front cover".

**Comment by sheik124** [comment]
NBD if you can't change it, now that I know how it's working, I can just add a proper "folder.jpg" to those with missing art. It's something I was working on automating anyways so that my library looks neater in Explorer and so that I don't have Windows' dinky little 200x200 automatically generated ones muddling things up too.

I'm just happy to be able to control foobar in full screen games without having to fiddle with multimedia keys and different "Fn" layer mappings on different keyboards.

**Comment by z3ath** [comment]
What I think I'll do is default to the embedded artwork and add an option to override it (larger/external). I'll take a look at FLAC/M4A embedded artwork while I'm in there too, not sure what the situation might be there. 

It'll be a couple days before I have time to work on this as I don't have a Windows machine ready to go right now.

Thanks for bringing it up with a detailed report.

**Comment by sheik124** [comment]
No problem, take your time. Thank you for taking the time to make this, I couldn't find any other foobar miniplayers that stayed on top of full screen applications. Only other option would've been a klutzy custom layout for foobar that I would have to switch back and forth between while toggling foobar's "Always On Top" setting.

**Comment by sheik124** [comment]
Oh, and one WMA file as well lol. It's weird, removing "folder.jpg" from my big "mixed" folder did get all of the MP3s in there to start showing their embedded art correctly.

**Comment by z3ath** [comment]
Hi, sorry, I had some delays getting around to this issue.

I've just uploaded a release (`0.1.0`) that should address the issues you mentioned. It has some extra bits I wanted to add too, there's a full changelog on the release page. I've only done minimal testing on my own machine so please let me know if you have any issues with the release.

I managed to get FLAC album artwork loading. I didn't readily find any M4A/WMA files with attached artwork in my collection so there is probably still an issue there. If you could provide some sample files I'll have a go at getting them working too.

Thanks

**Comment by sheik124** [comment]
Appears to be fixed, at least on the first problem FLAC file I ran across!

![image](https://user-images.githubusercontent.com/2312934/109513145-cc74d000-7a72-11eb-843c-caabfb3a54a1.png)

Lucked into an M4A file that isn't working:

![image](https://user-images.githubusercontent.com/2312934/109513392-0cd44e00-7a73-11eb-8663-8f95167192c3.png)

https://www104.zippyshare.com/v/w3gESWQH/file.html

Had to give the config.ini a quick and dirty edit. I've got a 1280x800 screen and it was drawing it somewhere outside it by default.

**Comment by z3ath** [comment]
Thanks, I've updated the position value in the release. I'm getting a 403 (forbidden) error from the link, could you upload it to a different host?

**Comment by sheik124** [comment]
Strange, never had that issue with Zippyshare before.

[mega.nz](https://mega.nz/file/O641HILR#lluFaZsm5uwj7VMwxPYRrpcR0-Ie7ctDTeMXX-9h2v4)

**Comment by z3ath** [comment]
That one's working, I'll try to get an updated release out tomorrow

**Comment by z3ath** [comment]
Hi, there's a release up with M4A support now. Please let me know if there's any issues with it.
